font_family      JetBrainsMono Nerd Font
font_size        11.0

background_opacity 0.78
background        #05010d
foreground        #fdf4ff
cursor            #f472b6
selection_foreground #05010d
selection_background #f9a8d4

color0  #05010d
color1  #be185d
color2  #22c55e
color3  #eab308
color4  #6366f1
color5  #f472b6
color6  #22d3ee
color7  #e5e7eb
color8  #111827
color9  #db2777
color10 #4ade80
color11 #facc15
color12 #818cf8
color13 #fb7185
color14 #38bdf8
color15 #f9fafb

shell /usr/bin/fish

