exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator

exec-once = waybar
exec-once = mako

exec-once = swaybg -i ~/.config/wallpapers/default.jpg -m fill

