general {
  disable_loading_bar = true
  grace = 0
  hide_cursor = true
  no_fade_in = false
}

background {
  monitor =
  path = ~/.config/wallpapers/default.jpg
  blur_passes = 4
  blur_size = 8
  noise = 0.03
  contrast = 1.05
  brightness = 0.88
  vibrancy = 0.18
}

input-field {
  monitor =
  size = 280, 42
  rounding = 22
  outline_thickness = 4
  dots_size = 0.24
  dots_spacing = 0.18
  dots_center = true

  inner_color = rgba(05010dcc)
  outer_color = rgba(831843ff)
  font_color = rgba(fdf4ffff)
  fade_on_empty = true

  placeholder_text = < welcome back >
  fail_text = < nope >

  shadow_size = 40
  shadow_color = rgba(f472b644)
  position = 0, -120
  halign = center
  valign = center
}

label {
  monitor =
  text = $USER
  font_size = 18
  color = rgba(fdf4ffff)
  shadow_size = 24
  shadow_color = rgba(000000aa)

  position = 0, -180
  halign = center
  valign = center
}

