windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(org.gnome.Calculator)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, title:^(Picture-in-Picture)$

windowrulev2 = opacity 0.90 0.82, class:^(kitty)$
windowrulev2 = opacity 0.92 0.84, class:^(Rofi)$
windowrulev2 = opacity 0.94 0.88, class:^(waybar)$

windowrulev2 = suppressevent maximize, class:.*

